image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - ghi/node_modules/
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
